[2024-12-03 20:02:39] local.ERROR: Cannot use Illuminate\Support\Facades\DB as DB because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use Illuminate\\Support\\Facades\\DB as DB because the name is already in use at /home/admin/webserver/web/api.sergivanov.ru/public_html/app/Http/Controllers/ServicesController.php:11)
[stacktrace]
#0 {main}
"} 
[2024-12-03 20:02:53] local.ERROR: Cannot use Illuminate\Support\Facades\DB as DB because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use Illuminate\\Support\\Facades\\DB as DB because the name is already in use at /home/admin/webserver/web/api.sergivanov.ru/public_html/app/Http/Controllers/ServicesController.php:11)
[stacktrace]
#0 {main}
"} 
[2024-12-03 20:02:55] local.ERROR: Cannot use Illuminate\Support\Facades\DB as DB because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use Illuminate\\Support\\Facades\\DB as DB because the name is already in use at /home/admin/webserver/web/api.sergivanov.ru/public_html/app/Http/Controllers/ServicesController.php:11)
[stacktrace]
#0 {main}
"} 
